name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  update_resume:
    name: Update resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: xu-cheng/texlive-action/small@v1
        name: Build resume
        with:
          # note, it is important to include the packages used by the resume
          # here, otherwise the CI job will fail
          run: |
            apk add make
            tlmgr install pbox minibox
            make persistent
      - name: Commit updated persistent resume
        run: |
          git config --global user.name 'Devin Lehmacher'
          git config --global user.email 'lehmacdj@users.noreply.github.com'
          git commit -am "Automated build job: Update persistent resume"
          git push
