name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  update_resume:
    name: Update resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build resume
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make persistent
      - name: Commit/push new resume
      - uses: actions-js/push@v1
