name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  update_resume:
    name: Update resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: xu-cheng/texlive-action/full@v1
        name: Build resume
        with:
          run: |
            apk add make
            make persistent
      - name: Commit updated persistent resume
        run: |
          git config --global user.name 'Devin Lehmacher'
          git config --global user.email 'lehmacdj@users.noreply.github.com'
          if git diff --quiet -- files/Devin_Lehmacher.pdf; then
            echo "Resume unchanged"
          else
            git add files/Devin_Lehmacher.pdf
            git commit -am "Automated build job: Update persistent resume"
            git push
          fi
